### PR TITLE
Second Patch for Power Button

### PR DESCRIPTION
**Pull request by Waitsnake**
This patch of OSX power button leads to following behavior:
- press power button less than 1.5 sec -> nothing happens
- press power button more than 1.5 sec but less than 8 sec -> shows
  shutdown dialog
- press power button more than 8 sec -> system powers off

### CODE REVIEW

**Comment by pkamb** [comment]
This is great! Just tested (2013 13" rMBP, 10.9.1) alongside [PowerKey](https://github.com/pkamb/PowerKey), and the app is useful again and back to roughly pre-Mavericks behavior. Thanks, and looking forward to seeing this pulled into power_fixer.

Others, please test!

**Comment by ghost** [comment]
I've tried the version by @Stino out on my rMBP and I am not having the same result. When I build and run it, it does block the dialog box, but when I hold the power button for 4 seconds it does a hard power cycle (not 8). I'm not sure if this is wait time that is system dependent or if I am doing something wrong.

**Comment by pkamb** [comment]
Hmm, interesting @y0shiy0shi. What hardware are you using? Was this a fresh install, or was a previous version of power_fixer already running?

**Comment by ghost** [comment]
latest rMBP 15" on 10.9.1. Previous power_fixer was removed and system rebooted to verify.

**Comment by pkamb** [comment]
Details of @Stino's changes:  
http://binchewer.org/blog/index.php?id=1#c000027

**Comment by pkamb** [comment]
[Broken by OS X 10.9.2](https://github.com/binchewer/power_fixer/issues/9):

```
[ERROR] No call sub_10003dcb5. Patched already? (find_patch_place2, 435)
All done.
```

**Pull request closed without merging**
